name: sitges
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animations: ^2.0.8
  dartz: ^0.10.1
  flutter_advanced_segment: ^3.0.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  location: ^5.0.2+1
  stack_trace: any
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  socket_io_client: ^2.0.3+1
  provider: ^6.0.5
  rxdart: ^0.27.7
  collection: ^1.17.0
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  pretty_dio_logger: ^1.3.1
  carousel_slider: ^4.2.1
  custom_sliding_segmented_control: ^1.8.1
  flutter_custom_tab_bar: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
